{% set name = "PDielec" %}
{% set version = "8.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

  sha256: a6ee8062d58dafc40b1efba6be2c791da9ea635c33b168088566ac25ebf4bfaf


build:
  noarch: python
  number: 0
  entry_points:
    - preader=PDielec.preader:main
    - p2cif=PDielec.p2cif:main
    - pickled_reader=PDielec.pickled_reader:main
    - pdcompare=PDielec.pdcompare:main
    - pdgui=PDielec.pdgui:main
    - pdmake=PDielec.pdmake:main
    - vibanalysis=PDielec.vibanalysis:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - scipy
    - scikit-learn
    - pyqt
    - pyopengl
    - xlsxwriter
    - pyyaml
    - openpyxl
    - termcolor
    - imageio
    - imageio-ffmpeg
    - ffmpeg
    - requests
    - beautifulsoup4
    - bleach
    - docutils
    - psutil
    - pygments
    - dill

test:
  imports:
    - PDielec
  commands:
    - preader --help
    - p2cif --help
  requires:
    - pip

about:
  home: https://github.com/JohnKendrick/PDielec
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PDielec package for the calculation of THz and infrared spectra
  doc_url: https://johnkendrick.github.io/PDielec
  dev_url: https://github.com/JohnKendrick/PDielec

extra:
  recipe-maintainers:
    - JohnKendrick
    - ADBurnett
